### ISSUE TITLE
The demo doesn't work

### ISSUE THREAD

**Issue by zeus6999** [DimiMikadze/orca#132]
The demo doesn't work. It is impossible to signup

You can give me an Email and a password to see how it works?

Regards

**Comment by DimiMikadze** [comment]
Hi @zeus6999 thanks for reporting an issue.

Email sign-up doesn't work because Mailgun disabled our account because their system thought that we exposed accidentally our Mailgun API Key. This is not the case we just have a sample text in the `.env.example` file, and we are waiting for their support to re-enable our account.

Meanwhile, you can test the app by installing it locally by running `npx create-orca-app my-app`.

**Comment by ptaberg** [comment]
@DimiMikadze, I think would be better to provide ready creds to surf around the demo. Usually, they are set by default in the fields or under them.

**Comment by DimiMikadze** [comment]
Hi guys, finally Mailgun has enabled our account. 

But due to your request, we made the requirement of email verification optional. Super admin users can change it from the UI. And for the https://community.getorca.org/ it is set to false. It means you can sign up for the app without email verification. 

If you are interested this is the PR for that changes: https://github.com/DimiMikadze/orca/pull/134

To update channels and have access to the Admin UI, you still need an Admin user. To see that you'll need to create your version of Orca and create an Admin user. https://getorca.org/docs/getting-started/installation

Once again thanks for reporting an issue.
