### ISSUE TITLE
Heroku Buildpack

### ISSUE THREAD

**Issue by BosEriko** [DimiMikadze/orca#17]
**Is your feature request related to a problem? Please describe.**

This is not really a problem but it would be cool if there's a simpler way to host it.

**Describe the solution you'd like**

It would be nice to have a Heroku Buildpack button on the README.md that will start a Heroku Project containing create-social-network.

**Comment by DimiMikadze** [comment]
Hi @BosEriko thanks for the issue, but we are not planning to implement this functionality, since we have two separated projects, Nodejs API and React static frontend. For NodeJS API we have decided to use Heroku and for frontend Netlify, if you follow the instructions it is simple enough to deploy both of them, thanks!
