### ISSUE TITLE
unable to create template application

### ISSUE THREAD

**Issue by nareshgnT** [DimiMikadze/orca#18]
**Describe the bug**

Unable to create template using ```npx create-social-network my-network``` in macOS. Getting ```fatal: Unable to find remote helper for 'git+https' ```error.

(Write your answer here.)

**System**

Node.js version: v10.11.0
NPM or Yarn version: NPM 6.8.0
Operating system: Mac os 10.14.6 (18G103)

**Steps to reproduce**
(Write your steps here:)

1. npx create-social-network my-network
2.
3.

**Expected behavior**

should be able to create template application my-network
**Actual behavior**

getting error ```fatal: Unable to find remote helper for 'git+https' ```

**Comment by DimiMikadze** [comment]
Hi @nareshgnT thanks for reporting the issue, it looks like you are not able to clone “https” repositories: https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone

I’ll try to push fix for this kind of scenarios tomorrow and let you know ✌️

**Comment by DimiMikadze** [comment]
@nareshgnT I've pushed new changes to repository and NPM package, now it first tries to clone via https and if it fails then tries to clone via ssh. Please try `npx create-social-network my-network` one more time and let me know if it fixes your issue 👍

**Comment by DimiMikadze** [comment]
Closing the issue, feel free to re-open it, if you still experience same problem.

**Comment by nareshgnT** [comment]
now i am getting below error, it fall back to ssh but ssh clone is not working.

```logs
Cloning into 'my-network'...
fatal: unable to find remote helper for 'git+https'
Cloning into 'my-network'...
git+git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error: Cloning of the repository failed.
```

**Comment by nareshgnT** [comment]
@DimiMikadze ^^^

**Comment by nareshgnT** [comment]
i am able to clone manually `create-social-network` repo both via https and ssh

**Comment by DimiMikadze** [comment]
thanks @nareshgnT i'm working on it, I'll let you know when i'll push fix for it 👍

**Comment by DimiMikadze** [comment]
@nareshgnT i think i've pushed fix for your problem, can you try to create project again and let me know, how it goes?

**Comment by DimiMikadze** [comment]
@nareshgnT you don't need to install dependencies manually, they are being installed while creating a template, so after creating an app you just need to `cd` into it and run `npm start` or `yarn start`.

If you git clone the repo by yourself and try to manually install dependencies that error will occur, because template is built with `Yarn Workspaces` and by running `yarn` in the root of project will install dependencies for `root` `api` and `frontend` projects, but `npm` doesn't supports yarn workspaces therefore you separately should install dependencies, e.g `cd api`  and `npm install` then `cd frontend` and  `npm install`

**Comment by DimiMikadze** [comment]
Once again thanks for reporting the issue!
