### ISSUE TITLE
 The app doesn't work.

### ISSUE THREAD

**Issue by SuleBenme** [DimiMikadze/orca#44]
Everything works fine in the beginning as you can see in the picture

![Skjermbilde (116)](https://user-images.githubusercontent.com/60656767/77450922-41b43b80-6df4-11ea-94e3-9e7edc09acfc.png)

But it doesn't work in the web browser
![Skjermbilde (115)](https://user-images.githubusercontent.com/60656767/77450918-40830e80-6df4-11ea-98f9-07b337de694c.png)

Node.js version: 12.13.0
NPM or Yarn version: 6.14.2

**Comment by DimiMikadze** [comment]
@SuleProgrammer demo database is being deleted and populated with demo data daily, it seems you have signed-in  in the app and after that database was reseted. 

https://github.com/dimimikadze/create-social-network#requirements-and-configuration

That's why it is recommended to create and connect your own database and CDN to the app.

To fix issue for now, clear localStorage and cookies to simulate sign out from the app.
