### ISSUE TITLE
Secret error

### ISSUE THREAD

**Issue by mandiladitya** [DimiMikadze/orca#74]
Hii
I clone the code and run replace all the MongoDB and api key 
But what is secret in .env
It gives me error data is not defined

**Comment by letoribo** [comment]
just an arbitrary string

**Comment by mandiladitya** [comment]
I got the error 
data is not defined in App.js 
Please help

**Comment by letoribo** [comment]
![data is not defined](https://user-images.githubusercontent.com/4941581/93387987-b7b0d100-f872-11ea-9f52-2117c5e24133.PNG)

**Comment by DimiMikadze** [comment]
Hi @mandiladitya, deleting the token from the local storage will resolve your problem. 

The error occurs because you are using a shared database that gets deleted and populated with demo data daily. 
https://github.com/dimimikadze/create-social-network#requirements-and-configuration

I recommend you to connect your own database to the application, so you avoid errors like this. We won't support a shared database in the near future anyway, you can install MongoDB on your local machine or create a free cloud database using MongoDB Atlas, and connect it to the app by just changing the `MONGO_URL` value in `api/.env` file.

**Comment by DimiMikadze** [comment]
Closing in favor of #81
